# Generated by Django 5.1.1 on 2024-09-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffattendance',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='is_on_shift',
            field=models.BooleanField(default=True),
        ),
    ]
