# Generated by Django 5.1.1 on 2024-09-11 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staffattendance_is_late_staffattendance_is_on_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffattendance',
            name='is_late',
        ),
        migrations.RemoveField(
            model_name='staffattendance',
            name='is_on_shift',
        ),
    ]
